### This code allows the manipulation of myosuite models based on tasks.

In [2]:
import myosuite
import gym
import imageio
import numpy as np
import os
import tqdm


In [3]:
from IPython.display import HTML
from base64 import b64encode
 
def show_video(video_path, video_width = 400):
   
  video_file = open(video_path, "r+b").read()
 
  video_url = f"data:video/mp4;base64,{b64encode(video_file).decode()}"
  return HTML(f"""""")

### <b>ReachV0</b>

### Display the environment in MuJoCo

In [1]:
import gym
import myosuite 
import time

#CenterReachOut-v0
#myoChallengeRelocateP1-v0


env = gym.make('CenterReachOut-v0')
env.reset()
    
for ep in range(1000):
    print(f'Episode: {ep} of 5')
    while True:
        #print("object: ", env.obs_dict['obj_pos'])
        #print("palm: ", env.obs_dict['palm_pos'])
        #print("qpos: ", env.obs_dict['hand_qpos'])
        #print("qvel: ", env.obs_dict['hand_qvel'])
        #print("reach: ", env.obs_dict['reach_err'])
        #print(env.sim.data.site_xpos[env.object_sid])
        for l in range(1):
            time.sleep(0.5)
            print(env.obs_dict['reach_err'])
            action = env.action_space.sample()
            # uncomment if you want to render the task
            env.mj_render()
            next_state, reward, done, info = env.step(action)
            state = next_state
        env.reset()
        if done: 
            break

MyoSuite:> Registering Myo Envs
    MyoSuite: A contact-rich simulation suite for musculoskeletal motor control
        Vittorio Caggiano, Huawei Wang, Guillaume Durandau, Massimo Sartori, Vikash Kumar
        L4DC-2019 | https://sites.google.com/view/myosuite
    
Episode: 0 of 5
[ 0.0109 -0.1395 -0.0177]
[ 0.0109 -0.1395 -0.0177]
[ 0.0109 -0.1395 -0.0177]
[-0.1391 -0.1395 -0.0177]
[-0.1891 -0.0395 -0.0177]
[ 0.1109  0.0605 -0.0177]
[ 0.1609 -0.0395 -0.0177]
[ 0.0109  0.1605 -0.0177]
[-0.1391  0.0605 -0.0177]
[-0.1391 -0.1395 -0.0177]
[-0.1391  0.0605 -0.0177]
[ 0.0109  0.1605 -0.0177]
[ 0.0109 -0.1395 -0.0177]
[-0.1391  0.0605 -0.0177]
[ 0.0109  0.1605 -0.0177]
[-0.1391  0.0605 -0.0177]
[ 0.0109  0.1605 -0.0177]
[ 0.1609 -0.0395 -0.0177]
[ 0.1109 -0.1395 -0.0177]
[ 0.1109 -0.1395 -0.0177]
[ 0.1109  0.0605 -0.0177]
[ 0.0109 -0.1395 -0.0177]
[ 0.1109  0.0605 -0.0177]
[ 0.1109 -0.1395 -0.0177]
[ 0.0109  0.1605 -0.0177]
[ 0.1609 -0.0395 -0.0177]
[ 0.0109 -0.1395 -0.0177]
[ 0.0109 -0.1395

KeyboardInterrupt: 

In [ ]:
)
            print(env.get_reward_dict(env.obs_dict))
            action = env.action_space.sample()
            # uncomment if you want to render the task
            env.mj_render()
            next_state, reward, done, info = env.step(action)
            state = next_state
        env.reset()
        if done: 
            break

In [ ]:
# random value as an action
action = env.action_space.sample()

observation_state, reward, done, info = env.step(action)

# myoElbowPose1D6MRandom-v0 is a pose-type task
# see definition here https://github.com/facebookresearch/myosuite/blob/1d45e4d5603a70487355902450006d3bd7828d43/myosuite/envs/myo/pose_v0.py#L89

print(f"Observation dimension {len(observation_state)}")
# Observation is composed of: qpos [1], qvel [1], act [6], pose_err [1]
print(f"Observation values: {observation_state}")

# Information about the task reward
print(f"Reward value: {reward}")

# Flag to check if the task is done
print(f"Is Done: {done}")

# All the info relative to the environment i.e. reward (dense/sparse), task is solved, ...
print(f"The overall info: {info.keys()}")
# Specifically, the information relative to the state
print(f"Info contained contained the info['state']: {info['state']['site_pos']}")


Observation dimension 169
Observation values: [-7.5936e-01  3.2282e-01 -3.2257e-01  7.5942e-01 -1.5329e-01  1.2439e+00
  5.6019e-01 -5.6047e-01 -1.2432e+00  1.5310e-01  3.9137e-01  3.1433e+00
 -3.9133e-01 -7.1712e-01 -4.2369e-03  3.4175e-02  3.7265e-01  8.1219e-01
 -5.4255e-01 -8.0604e-01  3.0218e-01 -1.3228e+00  1.6228e+00  2.5408e-01
  1.5874e+00  1.5811e+00  1.6226e+00  1.6407e-01  1.6151e+00  4.9521e-02
  1.3341e+00  2.6774e-01  1.4316e+00 -1.3600e-02  2.8641e-01 -2.6771e-01
 -3.4444e-02 -2.4034e-02 -5.3941e-04 -9.4007e-05  9.5322e-05  5.3448e-04
 -2.9152e-04  7.7956e-05 -6.9185e-04  7.2854e-04 -9.3400e-05  3.0101e-04
 -9.2296e-03  2.3119e-05  9.2024e-03 -1.5195e-02 -1.4808e-03  1.7162e-02
  2.0969e-02 -2.6229e-03 -6.5672e-03 -9.6148e-03 -3.4396e-02 -2.1466e-02
  9.2915e-03  1.1400e-02  7.2842e-03  3.0352e-03  2.6765e-03  5.3728e-03
  3.4624e-04 -7.0408e-05  8.0022e-03 -4.2585e-03  2.4337e-02  1.0154e-02
 -2.5587e-02  4.1683e-03 -5.3835e-03 -2.2840e-03 -6.5794e-02  3.4883e-02
  6.6

### Change Tasks targets

In [ ]:
env_fix = gym.make('myoArmPRandom-v0')
env_rand = gym.make('myoArmReachRandom-v0')

for ep in range(10):
  env_fix.reset()
  print(f"Episode {ep}, target: {env_fix.env.target_reach_range}")

for ep in range(10):
  env_rand.reset()
  print(f"Episode {ep}, target: {env_rand.env.target_reach_range}")


UnregisteredEnv: No registered env with id: myoArmPRandom-v0

### POSEV0


In [ ]:
import myosuite
import gym
import time


env = gym.make('myoHandReachFixed-v0')
env.reset()
for _ in range(1000):
    env.mj_render()
    env.step(env.action_space.sample())
    env.reset()

: 

In [ ]:
# random value as an action
action = env.action_space.sample()

observation_state, reward, done, info = env.step(action)

# myoElbowPose1D6MRandom-v0 is a pose-type task
# see definition here https://github.com/facebookresearch/myosuite/blob/1d45e4d5603a70487355902450006d3bd7828d43/myosuite/envs/myo/pose_v0.py#L89

print(f"Observation dimension {len(observation_state)}")
# Observation is composed of: qpos [1], qvel [1], act [6], pose_err [1]
print(f"Observation values: {observation_state}")

# Information about the task reward
print(f"Reward value: {reward}")

# Flag to check if the task is done
print(f"Is Done: {done}")

# All the info relative to the environment i.e. reward (dense/sparse), task is solved, ...
print(f"The overall info: {info.keys()}")
# Specifically, the information relative to the state
print(f"Info contained contained the info['state']: {info['state']['site_pos']}")


In [ ]:
# Only for Elbow, test different posture
env = gym.make('myoArmPoseFixed-v0')
# Sequence of test angles
AngleSequence = [60, 0, 80, 30]
# Flag to enable a sequence of different fixed targets
env.env.target_type = 'fixed'

env.reset()
frames = []
for ep in range(len(AngleSequence)):
    print("Ep {} of {} testing angle {}".format(ep, len(AngleSequence), AngleSequence[ep]))

    # Set the new target value
    env.env.target_jnt_value = [np.deg2rad(AngleSequence[int(ep)])]
    # Update the target value
    env.env.update_target()

    for _ in range(20):
        frames.append(env.sim.renderer.render_offscreen(
                        width=400,
                        height=400,
                        camera_id=0))
        o = env.get_obs()
        a = pi.get_action(o)[0]
        next_o, r, done, _ = env.step(a) # take an action based on the current observation
env.close()

os.makedirs('videos', exist_ok=True)
# make a local copy
skvideo.io.vwrite('videos/arm.mp4', np.asarray(frames),outputdict={"-pix_fmt": "yuv420p"})
show_video('videos/arm.mp4')

UnregisteredEnv: No registered env with id: myoArmPoseFixed-v0

### Moves Arm Model by changing actuator intensity 
//===============================================

In [ ]:

env = gym.make('ArmReachFixed-v0', normalize_act = False) #Change the task depending on what model/environment you want to use

env.reset()

env.env.init_qpos[:] = np.zeros(len(env.env.init_qpos),)
mjcModel = env.sim.model

print("Muscles:")
for i in range(mjcModel.na):
     a = print([i,mjcModel.actuator(i).name])

print("\nJoints:")
for i in range(mjcModel.njnt):
     b = print([i,mjcModel.joint(i).name])

    MyoSuite: A contact-rich simulation suite for musculoskeletal motor control
        Vittorio Caggiano, Huawei Wang, Guillaume Durandau, Massimo Sartori, Vikash Kumar
        L4DC-2019 | https://sites.google.com/view/myosuite
    
Muscles:
[0, 'DELT1']
[1, 'DELT2']
[2, 'DELT3']
[3, 'SUPSP']
[4, 'INFSP']
[5, 'SUBSC']
[6, 'TMIN']
[7, 'TMAJ']
[8, 'PECM1']
[9, 'PECM2']
[10, 'PECM3']
[11, 'LAT1']
[12, 'LAT2']
[13, 'LAT3']
[14, 'CORB']
[15, 'TRIlong']
[16, 'TRIlat']
[17, 'TRImed']
[18, 'ANC']
[19, 'SUP']
[20, 'BIClong']
[21, 'BICshort']
[22, 'BRA']
[23, 'BRD']
[24, 'ECRL']
[25, 'ECRB']
[26, 'ECU']
[27, 'FCR']
[28, 'FCU']
[29, 'PL']
[30, 'PT']
[31, 'PQ']
[32, 'FDS5']
[33, 'FDS4']
[34, 'FDS3']
[35, 'FDS2']
[36, 'FDP5']
[37, 'FDP4']
[38, 'FDP3']
[39, 'FDP2']
[40, 'EDC5']
[41, 'EDC4']
[42, 'EDC3']
[43, 'EDC2']
[44, 'EDM']
[45, 'EIP']
[46, 'EPL']
[47, 'EPB']
[48, 'FPL']
[49, 'APL']
[50, 'OP']
[51, 'RI2']
[52, 'LU_RB2']
[53, 'UI_UB2']
[54, 'RI3']
[55, 'LU_RB3']
[56, 'UI_UB3']
[57, 'RI4']
[58, '

<h2> Changing actuator activation levels for movement </h2>

In [ ]:

musc_fe = [mjcModel.actuator('LAT1').id] #Appends id values of actuators to list (Change depending on desired movement)
print(musc_fe)
L_range = round(1/mjcModel.opt.timestep) 
print(L_range)
skip_frame = 50


frames_sim = []
for iter_n in range(5):
    print("iteration: "+str(iter_n))
    res_sim = []
    act_val = 0
    ctrl = np.zeros(mjcModel.na,)
    for rp in range(10): 
        ctrl[musc_fe[0]] = 0
        increment = 1/L_range
        for s in range(L_range):
            if not(s%skip_frame):
                frame = env.sim.renderer.render_offscreen(
                                width=400,
                                height=400,
                                camera_id=0) #Arm Model context: id=0 (side cam) id = 1 (far front) , id  = 2 and 3 (close view front/back)
                frames_sim.append(frame)
            
            ctrl = np.zeros(mjcModel.na,)
            act_val =+ increment
            ctrl[musc_fe[0]] = act_val+increment                  
            env.step(ctrl)

os.makedirs('videos', exist_ok=True)
video_path = 'videos/test_policy.mp4'


imageio.mimsave(video_path, frames_sim, fps=30)

show_video(video_path)


[11]
500
iteration: 0
iteration: 1
iteration: 2
iteration: 3
iteration: 4
